### ISSUE TITLE
An empty draft shows 1 as the number of words.

### ISSUE THREAD

**Issue by alankley** [scripting/wordlandSupport#18] opened 2024-12-11 19:37 UTC
An empty draft lists 1 as the number of words.  Shouldn't it be 0?

<img width="762" alt="WordlandWordCount" src="https://github.com/user-attachments/assets/d3e15202-238c-4c72-9206-d4749bedde83" />

**Comment by scripting** [comment] 2024-12-11 20:28
Yes. That is a bug! :-)

**Comment by scripting** [comment] 2024-12-11 20:50
This should now be fixed. Please confirm.

**Comment by scotthansonde** [comment] 2024-12-12 11:06
When I start a new post, it shows "1 word" before I type anything. 

![CleanShot 2024-12-12 at 12 03 38](https://github.com/user-attachments/assets/bb2a6df7-d00c-42c1-ad2c-adb315e8f880)

When i type a couple of words then delete them, it shows "0 words"

![CleanShot 2024-12-12 at 12 06 15](https://github.com/user-attachments/assets/883ff0ab-8c24-40dd-8450-d93456f4109c)

**Comment by scripting** [comment] 2024-12-12 14:00
@scotthansonde -- thanks for the report. easy to reproduce. believe it or not, a little tricky to fix. will report back.

**Comment by scripting** [comment] 2024-12-12 15:47
@scotthansonde -- the problem should be fixed, it wasn't as tricky as I imagined, just took a bit of detective work to find where the problem was. 

https://daveverse.wordpress.com/2024/12/12/a-bug-fixed-and-excessively-explained/

**Closed** 2024-12-12 16:39 UTC
